---
abstract: 'HTML Form Creation, Rendering and Validation Framework'
author:
  - 'Carl Franks'
build_requires:
  CGI: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Captcha::reCAPTCHA: 0.93
  Class::Accessor::Chained::Fast: 0
  Class::MOP::Method: 0
  Clone: 0.31
  Config::Any: 0.18
  Crypt::CBC: 0
  Crypt::DES: 0
  Data::Visitor: 0.26
  Date::Calc: 0
  DateTime: 0.54
  DateTime::Format::Builder: 0.7901
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 1.2000
  DateTime::Locale: 0.45
  Email::Valid: 0
  Exporter: 5.57
  File::ShareDir: 0
  HTML::Scrubber: 0
  HTML::TokeParser::Simple: 3.14
  HTTP::Headers: 1.64
  Hash::Flatten: 0
  IO::File: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::Maketext: 0
  Module::Pluggable: 0
  Moose: 1.00
  Moose::Meta::Attribute::Custom::Trait::Chained: 0
  MooseX::Aliases: 0
  MooseX::ChainedAccessors::Accessor: 0.02
  MooseX::SetOnce: 0
  Number::Format: 0
  Path::Class::File: 0
  Readonly: 0
  Regexp::Common: 0
  Task::Weaken: 0
  Template: 0
  YAML::XS: 0.32
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/fireartist/HTML-FormFu.git
version: 0.09003_01
