---
abstract: 'HTML Form Creation, Rendering and Validation Framework'
author:
  - 'Carl Franks <cpan@fireartist.com>'
build_requires:
  CGI: 3.37
  POSIX: 0
  Test::Aggregate::Nested: 0.371
  Test::Exception: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu
no_index:
  directory:
    - examples
requires:
  Carp: 0
  Class::Accessor::Chained::Fast: 0
  Class::MOP::Method: 0
  Clone: 0.31
  Config::Any: 0.18
  Cwd: 0
  Data::Visitor: 0.26
  Data::Visitor::Callback: 0
  Date::Calc: 0
  DateTime: 0.54
  DateTime::Format::Builder: 0.7901
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 1.2000
  DateTime::Locale: 0.45
  Email::Valid: 0
  Encode: 0
  Exporter: 5.57
  Fatal: 0
  File::Copy: 0
  File::Find: 0
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  HTML::Scrubber: 0
  HTML::TokeParser::Simple: 3.14
  HTTP::Headers: 1.64
  Hash::Flatten: 0
  IO::File: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::Maketext: 0
  Module::Pluggable: 0
  Moose: 1.00
  Moose::Role: 0
  Moose::Util: 0
  MooseX::Aliases: 0
  MooseX::Attribute::Chained: v1.0.1
  MooseX::SetOnce: 0
  Number::Format: 0
  Path::Class::File: 0
  Readonly: 0
  Regexp::Common: 0
  Scalar::Util: 0
  Storable: 0
  Task::Weaken: 0
  YAML::XS: 0.32
  perl: 5.008001
resources:
  repository: git://github.com/fireartist/HTML-FormFu.git
version: 1.00
